branch-defaults:
  aws:
    environment: brain-score-web-dev
global:
  application_name: brain-score.web
  branch: null
  default_ec2_keyname: jjpr
  default_platform: Docker 18.09.9-ce
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
