"""
Django settings for web project.

Generated by 'django-admin startproject' using Django 2.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import boto3
import json
import os
from botocore.exceptions import NoCredentialsError
import logging
logger = logging.getLogger(__name__)


def get_secret(secret_name, region_name):
    session = boto3.session.Session()
    client = session.client(
        service_name='secretsmanager',
        region_name=region_name
    )
    get_secret_value_response = client.get_secret_value(
        SecretId=secret_name
    )
    return json.loads(get_secret_value_response['SecretString'])


REGION_NAME = "us-east-2"

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
try:
    SECRET_KEY = get_secret("brainscore-django-secret-key", REGION_NAME)["SECRET_KEY"]
except NoCredentialsError:
    SECRET_KEY = 'dummy'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False") == "True"

# ALLOWED_HOSTS Configuration (simplified with middleware approach)
hosts_list = os.getenv("DOMAIN", "localhost:brain-score-web-dev.us-east-2.elasticbeanstalk.com").split(":")
if os.getenv("DJANGO_ENV") == 'development': 
    hosts_list.append('127.0.0.1')
    hosts_list.append('localhost')

# Add Elastic Beanstalk domains with wildcard support
hosts_list.extend([
    "brain-score-web-dev-updated.eba-e8pevjnc.us-east-2.elasticbeanstalk.com",
    "Brain-score-web-prod-updated.eba-e8pevjnc.us-east-2.elasticbeanstalk.com", 
    "Brain-score-web-staging.eba-e8pevjnc.us-east-2.elasticbeanstalk.com",
    "*.eba-e8pevjnc.us-east-2.elasticbeanstalk.com",  # Wildcard for any new environments
    "127.0.0.1"
])

# Security note: We do NOT add suspicious domains like:
# - *.cprapid.com (known scanning service)
# - Domains that look like IP addresses with dashes
# These will be rejected by Django's ALLOWED_HOSTS security feature

# MIDDLEWARE-BASED HEALTH CHECK SOLUTION
# Since we now handle health checks via middleware, we can keep ALLOWED_HOSTS much cleaner
if os.getenv("DJANGO_ENV") != 'development':
    print("🔒 SECURITY: Using middleware-based health check solution")
    print("🔒 INFO: Health checks handled by HealthCheckMiddleware - no AWS IPs needed in ALLOWED_HOSTS")
    
    # We can now avoid adding any AWS IPs to ALLOWED_HOSTS!
    # The middleware handles health checks before ALLOWED_HOSTS validation
    
    # Only add if you have specific non-health-check traffic from AWS
    add_aws_ips = os.getenv("FORCE_AWS_IPS", "false").lower() == "true"
    
    if add_aws_ips:
        print("🔒 WARNING: FORCE_AWS_IPS enabled - adding minimal AWS ranges")
        # Only add if absolutely necessary for non-health-check traffic
        emergency_ips = ["172.31.0.0/16"]  # Private VPC range only
        hosts_list.extend(emergency_ips)
        print(f"🔒 Added minimal AWS ranges: {emergency_ips}")
    else:
        print("🔒 SECURE: No AWS IPs in ALLOWED_HOSTS - maximum security achieved")
    
    print("🔒 SECURITY: Middleware-based configuration completed")

# Set ALLOWED_HOSTS (clean and simple with middleware handling health checks)
ALLOWED_HOSTS = hosts_list

print(f"🔒 ALLOWED_HOSTS configured: {len(ALLOWED_HOSTS)} entries")
if DEBUG:
    print(f"🔒 DEBUG: ALLOWED_HOSTS = {ALLOWED_HOSTS}")
else:
    print(f"🔒 PRODUCTION: {len(ALLOWED_HOSTS)} domain entries (health checks handled by middleware)")


# Allows E-mail use
# After 6/1/22, Google removed login with username/password from "less secure apps" (i.e. Django)
# django_gmail_password thus is an app-specific login for Gmail (adds Django as authorized login for Gmail)
try:
    email_secrets = get_secret("brainscore-email", REGION_NAME)
except NoCredentialsError:
    email_secrets = {'host': None, 'address': None, 'password': None, 'django_gmail_password': None}
EMAIL_USE_TLS = True
EMAIL_HOST = email_secrets["host"]
EMAIL_PORT = 587
EMAIL_HOST_USER = email_secrets["address"]
EMAIL_HOST_PASSWORD = email_secrets["django_gmail_password"]

LOGOUT_REDIRECT_URL = '/'

# Application definition

INSTALLED_APPS = [
    'benchmarks.apps.BenchmarksConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'compressor',
]

MIDDLEWARE = [
    'benchmarks.middleware.HealthCheckMiddleware',  # Handle health checks BEFORE security checks
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.gzip.GZipMiddleware',  # Compress HTTP responses
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Note: Health check security is now handled by HealthCheckMiddleware

ROOT_URLCONF = 'web.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'benchmarks.context_processors.common_variables',
            ],
        },
    },
]

WSGI_APPLICATION = 'web.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases
db_secret_name = os.getenv("DB_CRED", "brainscore-1-ohio-cred-migrated")

def get_db_info():
    if os.getenv("DJANGO_ENV") == "test": # web test db
        secrets = get_secret(db_secret_name, REGION_NAME)
        return {
            'default': {
                'ENGINE': 'django.db.backends.postgresql_psycopg2',
                'NAME': 'web_tests',
                'USER': 'postgres',
                'PASSWORD': secrets["password"],
                'HOST': secrets["host"],
                'PORT': '5432',
                'TEST': {
                    'NAME': 'web_tests',  # This tells Django to use this exact name for tests
                }
            }
        }
    elif os.getenv("DJANGO_ENV") == "development":
        from dotenv import load_dotenv; load_dotenv()

        return {
            'default': {
                'ENGINE': 'django.db.backends.postgresql_psycopg2',
                'NAME': 'dev',
                'USER': 'postgres',
                'PASSWORD': os.getenv('DB_PASSWORD'),
                'HOST': os.getenv('DB_HOST'),
                'PORT': '5432'
            }
        }
    try:
        secrets = get_secret(db_secret_name, REGION_NAME)
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.postgresql_psycopg2',
                'NAME': secrets["dbInstanceIdentifier"],
                'USER': secrets["username"],
                'PASSWORD': secrets["password"],
                'HOST': secrets["host"],
                'PORT': secrets["port"]
            }
        }
    except NoCredentialsError:
        if 'RDS_DB_NAME' in os.environ:  # when deployed to AWS, use environment settings for database
            DATABASES = {
                'default': {
                    'ENGINE': 'django.db.backends.postgresql_psycopg2',
                    'NAME': os.environ['RDS_DB_NAME'],
                    'USER': os.environ['RDS_USERNAME'],
                    'PASSWORD': os.environ['RDS_PASSWORD'],
                    'HOST': os.environ['RDS_HOSTNAME'],
                    'PORT': os.environ['RDS_PORT'],
                }
            }
        else:  # for deployment, use local sqlite
            DATABASES = {
                'default': {
                    'ENGINE': 'django.db.backends.sqlite3',
                    'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
                }
            }
    return DATABASES


DATABASES = get_db_info()

# Cache Configuration
# https://docs.djangoproject.com/en/4.0/topics/cache/
def get_cache_config():
    '''
    Use CACHE_ENV=staging for staging, CACHE_ENV=production for production, CACHE_ENV=development for development.
    '''
    
    env = os.getenv("CACHE_ENV", os.getenv("DJANGO_ENV", "development"))

    # 1) Local dev → in-memory
    if env == "development":
        cfg = {
            'default': {
                'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
                'LOCATION': 'brain-score-default-cache',
                'TIMEOUT': 300,
            }
        }
        print(f"[CACHE] environment={env} → using {cfg['default']['BACKEND']} @ {cfg['default']['LOCATION']}")
        return cfg

    # 2) Staging / Production → Redis
    if env in ("staging", "production"):
        secret_name = {
            "staging": "brainscore-valkey-staging",
            "production": "brainscore-valkey-production",
        }[env]
        try:
            secrets = get_secret(secret_name, REGION_NAME)
            host = secrets["host"]
            port = secrets.get("port", 6379)
        except Exception as e:
            # couldn’t load secrets → fall back
            print(f"Cache secret load failed ({e}), using locmem fallback")
            return {
                'default': {
                    'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
                    'LOCATION': 'brain-score-fallback-cache',
                    'TIMEOUT': 300,
                }
            }
        USE_REDIS_TUNNEL = os.getenv("USE_REDIS_TUNNEL") == "true"
        if USE_REDIS_TUNNEL:
            host = "127.0.0.1"
            scheme = "rediss"
        else:
            scheme = "rediss"

        timeout = 7*24*3600 if env == "staging" else 30*24*3600
        prefix = f"brainscore:{env}"
        redis_cfg = {
                'BACKEND': 'django_redis.cache.RedisCache',
                'LOCATION': f"rediss://{host}:{port}/0",
                'TIMEOUT': timeout,
                'OPTIONS': {
                    'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                    'CONNECTION_POOL_KWARGS': {
                        'max_connections': 50,
                        'socket_timeout': 5,
                        'socket_connect_timeout': 5,
                        'retry_on_timeout': True,
                        'health_check_interval': 30,
                    },
                    "SERIALIZER": "django_redis.serializers.pickle.PickleSerializer",
                    'COMPRESSOR': 'django_redis.compressors.zlib.ZlibCompressor',
                    'IGNORE_EXCEPTIONS': True,
                },
                'KEY_PREFIX': prefix,
                'VERSION': 1,
            }
    
        print(f"[CACHE] environment={env} → using {redis_cfg['BACKEND']} @ {redis_cfg['LOCATION']}")
        return {'default': redis_cfg, 'redis': redis_cfg}

    # 3) Fallback
    cfg = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'brain-score-fallback-cache',
            'TIMEOUT': 300,
        }
    }
    print(f"[CACHE] environment={env} → fallback {cfg['default']['BACKEND']}")
    return cfg

CACHES = get_cache_config()

# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

# Security settings for headers and cookies  
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

# Additional security settings to prevent Host header attacks
USE_X_FORWARDED_HOST = False  # Prevent Host header spoofing through proxies
USE_X_FORWARDED_PORT = False  # Prevent port spoofing
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True


LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/New_York'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = 'static/'
STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'compressor.finders.CompressorFinder',
)

# compress
COMPRESS_PRECOMPILERS = (
    ('text/less', 'lessc {infile} {outfile}'),
    ('text/x-sass', 'sass {infile} {outfile}'),
)

AUTH_USER_MODEL = 'benchmarks.User'

# Logging
log_level = 'DEBUG' if DEBUG else 'INFO'
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'basic': {'format': '%(asctime)s %(name)-15.15s %(levelname)-8.8s %(message)s'}
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'basic',
        },
        'file': {
            'level': log_level,
            'class': 'logging.FileHandler',
            'formatter': 'basic',
            'filename': os.path.join(BASE_DIR, 'django.log'),
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'],
            'level': log_level,
            'propagate': True,
        },
    },
}

# Cache refresh token for triggering cache invalidation
try:
    # Try to get the token from AWS Secrets Manager first
    cache_refresh_secrets = get_secret("brainscore-cache-refresh", REGION_NAME)
    CACHE_REFRESH_TOKEN = cache_refresh_secrets["token"]
except Exception as e:  # Catch all exceptions, not just NoCredentialsError
    # Fall back to environment variable
    CACHE_REFRESH_TOKEN = os.getenv("CACHE_REFRESH_TOKEN")
    # For development only - generate a token if none exists
    if not CACHE_REFRESH_TOKEN and DEBUG:
        import secrets
        CACHE_REFRESH_TOKEN = secrets.token_hex(16)
        print(f"Generated CACHE_REFRESH_TOKEN: {CACHE_REFRESH_TOKEN}")
        # If in DEBUG mode, visit http://localhost:8000/debug/show_token/ to see the token